name: "my joke action"

description: "use an external API to retreive and disply a joke"

outputs:
  joke-output:
    description: The resulting joke from the icanhazdadjokes API

runs:
  using: "node16"
  main: "node.js"